# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20181105_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaches',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
