# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-24 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20181105_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='partially_done',
            new_name='institute',
        ),
        migrations.AddField(
            model_name='teaches',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
