# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-24 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20190324_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Subject Code'),
        ),
    ]
