# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_auto_20190324_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, help_text='Email of requester', max_length=250, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Phone of requester', max_length=250, null=True, verbose_name='Phone')),
                ('usn', models.CharField(blank=True, help_text='Username of requester', max_length=250, null=True, verbose_name='USN')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='institute',
            new_name='partially_done',
        ),
    ]
