# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-11 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20190411_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='partially_done',
            new_name='institute',
        ),
    ]
