# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20190411_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptrack',
            name='date_stamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otptrack',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
