# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20190411_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Subject Name'),
        ),
    ]
