# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20190411_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaches',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject Name'),
        ),
    ]
