# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_auto_20190423_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='d_type',
            field=models.CharField(choices=[('teaching', 'teaching'), ('non-teaching', 'non-teaching')], default='teaching', max_length=15),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject Name'),
        ),
    ]
