# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20190423_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
