# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20190424_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='This is used to test the data uploaded.', verbose_name='Test Mode'),
        ),
    ]
