# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-21 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_auto_20190424_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='full_name',
            field=models.CharField(blank=True, help_text='Name of the department', max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Short name of the department', max_length=250, verbose_name='Name'),
        ),
    ]
