# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-11 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_studentconsolidatedreport_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='code',
            field=models.CharField(help_text='Mandatory to enter two characters', max_length=2, verbose_name='Form Code'),
        ),
    ]
