# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-25 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_auto_20190411_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Feedback Title')),
                ('year', models.IntegerField(default=2019, verbose_name='Year')),
            ],
        ),
    ]
