# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_auto_20190520_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentconsolidatedreport',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Department'),
        ),
    ]
