# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0026_feedbackprocess_p2p'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedreport',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackProcess'),
        ),
    ]
